### ISSUE TITLE
[NavisensMap] Loading tiles offline

### ISSUE THREAD

**Issue by jax79sg** [navisens/Android-Plugin#3]
Hi,

Instead of accessing a tile server, is it currently possible in the API to either (1) load offline tiles (E.g. http://davidrs.com/wp/phonegap-3-0-leaflet-offline-maps/) , or (2) load a scaled image (E.g. https://gis.stackexchange.com/a/82952)? 

Thanks.

**Comment by lucasnavisens** [comment]
Hi,

Currently it isn't supported but we will consider adding it to our roadmap. 
Of course you can use your own visualization systems with our SDK.

Cheers.

**Comment by jax79sg** [comment]
Hi,

Thanks for the update.
